org:
  softek:
    company:
      addrs: bengalor
      id: 1234
      name: softek
      size: 100
    ename: sush
    eno: 100
    fav-colours:
    - red
    - pink
    - green
    idDetails:
      aadarid: 1234
      voterid: 1f4567hg
    nickName: sush,k,gowda
    phoneNumbers: 12343456778,23445556
